### ISSUE TITLE
Support for multiple build configurations?

### ISSUE THREAD

**Issue by stueynet** [bamlab/generator-rn-toolbox#119]
We use different icons for our development / staging builds and the production build to allow people to have both on their phone simultaneously. Is there a way to add multiple icon sets so we can configure the correct one for each build configuration?

**Comment by Almouro** [comment]
Hi @stueynet, I can see two possibilities for that:

## Overriding the assets when deploying depending on the configuration

## Add an option to the generator to specify *build type*.

Then on Android, change [the behaviour here](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/imageGenerator.js#L135), so that you can specify the build configuration you want to export to, so that created assets go into a `debug` folder for instance, instead of the `main` folder.

On iOS, the target folder could be [changed here](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/index.js#L108) to include the *scheme* name.
Then you could create a dev scheme with the dev iconset and a staging scheme with the staging iconset.

What do you think?
I don't think we'll have time to implement this in a foreseeable future, but PR are mostly welcome, if you're up to it! :)

**Comment by stueynet** [comment]
Thanks! I will have a look and see. I was thinking --scheme=myAppDev

**Comment by Almouro** [comment]
Hi @stueynet, I think you should now be able to do what you want with the PR I link :)
Feel free to reopen the issue if that's not the case!
