### ISSUE TITLE
The launch image set name "LaunchImage" did not have any applicable content.

### ISSUE THREAD

**Issue by DenJohX** [bamlab/generator-rn-toolbox#35]
Xcode throws that error on compile.

My setup:
Xcode 7
RN 0.34

Apparently the LaunchImage set is generated but with missing iPhone 5,6 images

![screen shot 2016-11-30 at 7 12 07 pm](https://cloud.githubusercontent.com/assets/991651/20778079/06406a56-b731-11e6-8798-a3c07b772c88.png)

**Comment by Almouro** [comment]
Hi @DenJohX, thanks for reporting the issue! 🚀 

I'm on Xcode 8.0 myself and it works even with the missing images for iOS 5,6. iOS 5 and 6 are not supported by React Native anyway :)
Is is possible for you to update?

If not, it seems according to [this answer](http://stackoverflow.com/questions/23168494/error-while-setting-app-icon-and-launch-image-in-xcode-5-1) that it might be due to a size problem.
What was the size of your original image? Was it bigger than 2208x2208px?

**Comment by yleflour** [comment]
Closing the issue

**Comment by dwilt** [comment]
I'm actually running into this at the moment.

**Comment by dwilt** [comment]
![image](https://user-images.githubusercontent.com/1065539/36186405-dee92ce0-110c-11e8-9466-f8b32a4363f8.png)

**Comment by dwilt** [comment]
My image was bigger than `2208 x 2208`
