### ISSUE TITLE
Error: Command failed: Invalid Parameter - -resize

### ISSUE THREAD

**Issue by ShailajaV** [bamlab/generator-rn-toolbox#77]
yo rn-toolbox:assets --icon path/icon.png
When i run the above command in my project i am getting following error:
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: Invalid Parameter - -resize

I am running this on android and my icon size is 192*192.

**Comment by Almouro** [comment]
Hi @ShailajaV, thanks for posting an issue here! :)

Are you running on Windows? If so, this problem seems to be related to [this ImageMagick issue](https://github.com/aheckmann/gm/issues/528).

Apparently, reinstalling ImageMagick with the legacy tools would fix it: 

![image](https://cloud.githubusercontent.com/assets/4534323/23771735/8f9b8896-0518-11e7-92c0-950dbdef8af0.png)

I don't have a Windows computer available. :\ Can you tell me if this works for you? :)

**Comment by ShailajaV** [comment]
Hi Almouro,
Thank you so much. It worked perfectly.

**Comment by Almouro** [comment]
@ShailajaV Great to hear!
I'm adding a *Troubleshooting* section in the Readme then :) (https://github.com/bamlab/generator-rn-toolbox/pull/78)

**Comment by ShailajaV** [comment]
Hi,

Its working fine after i restart it. Thanks for the help.

**Comment by sohamkumar-chauhan** [comment]
I am getting the same problem working with npm imagemagick package on the following function call:

im.convert([localPath, '-resize', '100x100', thumbPath], function (err, stdout, stderr)

What should I do?
